project:
  type: website
  output-dir: "../docs/en" 

website:
  title: "CBAT"
  navbar:
    logo: logo.png
    title: false
    left:
      - href: index.qmd
        text: CBAT
      - href: terms.qmd
        text: Terms of Use
      - href: usage.qmd
        text: How to use CBAT
    right:
      - href: https://cba-toolbox.github.io/CBAT/index.html
        text: Japanese
format:
  html:
    theme: minty
    css: styles.css
    toc: true