project:
  type: website
  output-dir: "../docs/en" 

website:
  title: "Cognitive & Behavioral Assessment Toolbox"
  navbar:
    left:
      - href: index.qmd
        text: CBAT
      - href: terms.qmd
        text: Terms of Use
      - href: usage.qmd
        text: How to use CBAT
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual