project:
  type: website
  output-dir: docs

website:
  title: "CBAT"
  navbar:
    logo: logo.png
    title: false
    left:
      - href: index.qmd
        text: CBAT
      - href: usage.qmd
        text: 利用方法
      - href: terms.qmd
        text: 利用規約とプラバシーポリシー
    right:
      - href: https://cba-toolbox.github.io/CBAT/en/index.html
        text: English
format:
  html:
    theme: minty
    css: styles.css
    toc: true