---
title: "利用規約とプラバシーポリシー"
editor: 
  markdown: 
    wrap: 72
---

# 利用規約

本利用規約（以下「本規約」と言います。）には、本サービスの提供条件及び当団体と登録ユーザーの皆様との間の権利義務関係が定められています。本サービスの利用に際しては、本規約の全文をお読みいただいたうえで、本規約に同意いただく必要があります。なお，本サービスへのログインをもって本規約に同意されたものとみなします。

## 第1条（適用）

1.  本規約は、本サービスの提供条件及び本サービスの利用に関する当団体と登録ユーザーとの間の権利義務関係を定めることを目的とし、登録ユーザーと当団体との間の本サービスの利用に関わる一切の関係に適用されます。

2.  当団体が当団体ウェブサイト上で掲載する本サービス利用に関する使用法（<https://cba-toolbox.github.io/CBAT/usage.html>）は、本規約の一部を構成するものとします。

3.  本規約の内容と、前項のルールその他の本規約外における本サービスの説明等とが異なる場合は、本規約の規定が優先して適用されるものとします。

## 第2条（定義）

本規約において使用する以下の用語は、各々以下に定める意味を有するものとします。

　（1）「サービス利用契約」とは、本規約を契約条件として当団体と登録ユーザーの間で締結される、本サービスの利用契約を意味します。

　（2）「知的財産権」とは、著作権、特許権、実用新案権、意匠権、商標権その他の知的財産権（それらの権利を取得し、またはそれらの権利につき登録等を出願する権利を含みます。）を意味します。

　（3）「投稿データ」とは、登録ユーザーが本サービスを利用して投稿その他送信するコンテンツ（文章、画像、動画その他のデータを含みますがこれらに限りません。）を意味します。

　（4）「当団体」とは、計算論的精神医学コロキウム（<https://cpcolloquium.github.io/cp_book/cpsy_colloquium.html>）を意味します。

　（5）「当団体ウェブサイト」とは、そのドメインがcbat.cpsy-lab.comまたはcba-toolbox.github.ioである、当団体が運営するウェブサイト（理由の如何を問わず、当社のウェブサイトのドメインまたは内容が変更された場合は、当該変更後のウェブサイトを含みます。）を意味します。

　（6）「登録ユーザー」とは、本規約に基づいて本サービスの利用者としての登録がなされた個人または法人を意味します。

　（7） 「本サービス」とは、当社が提供するCognitive & Behavioral
    Assessment
    Toolboxという名称のサービス（理由の如何を問わずサービスの名称または内容が変更された場合は、当該変更後のサービスを含みます。）を意味します。

## 第3条（登録） 

1.  本サービスの利用を希望する者（以下「登録希望者」といいます。）は、本規約を遵守することに同意し、かつ当団体の定める一定の情報（以下「登録事項」といいます。）を当団体の定める方法で当団体に提供することにより、当団体に対し、本サービスの利用の登録を申請することができます。

2.  当団体は、当団体の基準に従って、第1項に基づいて登録申請を行った登録希望者（以下「登録申請者」といいます。）の登録の可否を判断し、当団体が登録を認める場合にはその旨を登録申請者に通知します。登録申請者の登録ユーザーとしての登録は、当社が本項の通知を行ったことをもって完了したものとします。

3.  前項に定める登録の完了時に、サービス利用契約が登録ユーザーと当社の間に成立し、登録ユーザーは本サービスを本規約に従い利用することができるようになります。

4.  当社は、登録申請者が、以下の各号のいずれかの事由に該当する場合は、登録及び再登録を拒否することがあり、またその理由について一切開示義務を負いません。

　（1）当団体に提供した登録事項の全部または一部につき虚偽、誤記または記載漏れがあった場合

　（2）未成年者、成年被後見人、被保佐人または被補助人のいずれかであり、法定代理人、後見人、保佐人または補助人の同意等を得ていなかった場合

　（3）反社会的勢力等（暴力団、暴力団員、右翼団体、反社会的勢力、その他これに準ずる者を意味します。以下同じ。）である、または資金提供その他を通じて反社会的勢力等の維持、運営もしくは経営に協力もしくは関与する等反社会的勢力等との何らかの交流もしくは関与を行っていると当団体が合理的に判断した場合

　（4）過去当団体との本規約に違反した者またはその関係者であると当団体が合理的に判断した場合

　（5）第10条に定める措置を受けたことがある場合

　（6）その他、登録を適当でないと当団体が合理的に判断した場合

## 第4条（登録事項の変更） 

登録ユーザーは、登録事項に変更があった場合、当団体の定める方法により当該変更事項を遅滞なく当団体に通知するものとします。

## 第5条（パスワード及びユーザーIDの管理） 

1.  登録ユーザーは、自己の責任において、本サービスに関するパスワード及びユーザーIDを適切に管理及び保管するものとし、これを第三者に利用させ、または貸与、譲渡、名義変更、売買等をしてはならないものとします。

2.  パスワードまたはユーザーIDの管理不十分、使用上の過誤、第三者の使用等によって生じた損害に関する責任は登録ユーザーが負うものとします。

3.  前2項の規定は、本サービスのソーシャルログイン（Google, Apple,
    SNS（ソーシャルネットワーキングサービス）等を利用して行うアカウントへのログイン）対象アカウントに対応するユーザーID、パスワード、メールアドレスにおいても適用します。

## 第6条（料金及び支払方法） 

1.  登録ユーザーは、本サービス利用の対価として、別途当団体が定め、当団体ウェブサイトに表示する利用料金を、当団体が指定する支払方法により当団体に支払うものとします。

2.  登録ユーザーが利用料金の支払を遅滞した場合、登録ユーザーは年14.6％の割合による遅延損害金を当団体に支払うものとします。

## 第7条（禁止事項） 

登録ユーザーは、本サービスの利用にあたり、以下の各号のいずれかに該当する行為または該当すると当団体が合理的に判断する行為をしてはなりません。


　（1）法令に違反する行為または犯罪行為に関連する行為

　（2）当団体、本サービスの他の利用者またはその他の第三者に対する詐欺または脅迫行為

　（3）公序良俗に反する行為 

　（4）当団体、本サービスの他の利用者またはその他の第三者の知的財産権、肖像権、プライバシーの権利、名誉、その他の権利または利益を侵害する行為

　（5）本サービスを通じ、以下に該当し、または該当すると当団体が合理的に判断する情報を当団体または本サービスの他の利用者に送信すること

- 過度に暴力的または残虐な表現を含む情報
- コンピューター・ウィルスその他の有害なコンピューター・プログラムを含む情報
- 当団体、本サービスの他の利用者またはその他の第三者の名誉または信用を毀損する表現を含む情報
- 過度にわいせつな表現を含む情報 ・差別を助長する表現を含む情報
- 自殺、自傷行為を助長する表現を含む情報
- 薬物の不適切な利用を助長する表現を含む情報 ・反社会的な表現を含む情報
- チェーンメール等の第三者への情報の拡散を求める情報
- 他人に不快感を与える表現を含む情報 

　（6）本サービスのネットワークまたはシステム等に過度な負荷をかける行為 

　（7）当団体が提供するソフトウェアその他のシステムに対するリバースエンジニアリングその他の解析行為

　（8） 本サービスの運営を妨害するおそれのある行為 

　（9）当社のネットワークまたはシステム等への不正アクセス

　（10）第三者に成りすます行為 

　（11）本サービスの他の利用者のIDまたはパスワードを利用する行為 

　（12）当団体が事前に許諾しない本サービス上での宣伝、広告、勧誘、または営業行為

　（13）本サービスの他の利用者の情報の収集

　（14）当団体、本サービスの他の利用者またはその他の第三者に不利益、損害、不快感を与える行為

　（15）当団体ウェブサイト上で掲載する本サービス利用に関するルール（[https://cba-toolbox.github.io/CBAT/usage.html](https://cba-toolbox.github.io/CBAT/usage.html)）に抵触する行為

　（16）反社会的勢力等への利益供与

　（17）面識のない異性との出会いを目的とした行為

　（18）前各号の行為を直接または間接に惹起し、または容易にする行為

　（19）前各号の行為を試みること

　（20）その他、当団体が不適切であると合理的に判断する行為

## 第8条（本サービスの停止等）
当団体は、以下のいずれかに該当する場合には、登録ユーザーに事前に通知することなく、本サービスの全部または一部の提供を停止または中断することができるものとします。

（1）本サービスに係るコンピューター・システムの点検または保守作業を緊急に行う場合

（2）コンピューター、通信回線等の障害、誤操作、過度なアクセスの集中、不正アクセス、ハッキング等により本サービスの運営ができなくなった場合

（3）地震、落雷、火災、風水害、停電、天災地変などの不可抗力により本サービスの運営ができなくなった場合

（4） その他、当団体が停止または中断を必要と合理的に判断した場合

## 第9条（権利帰属） 

1. 当団体ウェブサイト及び本サービスに関する知的財産権は全て当団体または当団体にライセンスを許諾している者に帰属しており、本規約に基づく本サービスの利用許諾は、当団体ウェブサイトまたは本サービスに関する当団体または当団体にライセンスを許諾している者の知的財産権の使用許諾を意味するものではありません。

2. 登録ユーザーは、投稿データについて、自らが投稿その他送信することについての適法な権利を有していること、及び投稿データが第三者の権利を侵害していないことについて、当団体に対し表明し、保証するものとします。

3. 登録ユーザーは、投稿データについて、当団体に対し、世界的、非独占的、無償、サブライセンス可能かつ譲渡可能な使用、複製、配布、派生著作物の作成、表示及び実行に関するライセンスを付与します。また、他の登録ユーザーに対しても、本サービスを利用して登録ユーザーが投稿その他送信した投稿データの使用、複製、配布、派生著作物を作成、表示及び実行することについての非独占的なライセンスを付与します。

4. 登録ユーザーは、当団体及び当団体から権利を承継しまたは許諾された者に対して著作者人格権を行使しないことに同意するものとします。

## 第10条（登録抹消等） 

1. 当団体は、登録ユーザーが、以下の各号のいずれかの事由に該当する場合は、事前に通知または催告することなく、投稿データを削除もしくは非表示にし、当該登録ユーザーについて本サービスの利用を一時的に停止し、または登録ユーザーとしての登録を抹消することができます。

　（1） 本規約のいずれかの条項に違反した場合 

　（2）登録事項に虚偽の事実があることが判明した場合 

　（3）支払停止もしくは支払不能となり、または破産手続開始、民事再生手続開始、会社更生手続開始、特別清算開始もしくはこれらに類する手続の開始の申立てがあった場合

　（4） 24ヶ月以上本サービスへのログインがない場合 

　（5）当団体からの問い合わせその他の回答を求める連絡に対して30日間以上応答がない場合

　（6） 第3条第4項各号に該当する場合 

　（7）その他、当団体が本サービスの利用または登録ユーザーとしての登録の継続を適当でないと合理的に判断した場合

2. 前項各号のいずれかの事由に該当した場合、登録ユーザーは、当団体に対して負っている債務の一切について当然に期限の利益を失い、直ちに当社に対して全ての債務の支払を行わなければなりません。

## 第11条（本サービスの利用期間及び退会） 

1. 登録ユーザーの利用期間は、サービス利用契約成立時（本規約第3条3項）から登録抹消日（本規約第10条1項）または退会手続完了時（本契約同条次項）までとします。

2. 登録ユーザーは、当団体所定の退会手続を完了することにより、本サービスを解約することができます。

## 第12条（本サービスの内容の変更、終了） 

1. 当団体は、当団体の都合により、本サービスの内容を変更し、または提供を終了することができます。

2. 当団体が本サービスの提供を終了する場合、当団体のウェブサイトへの掲示をもって、登録ユーザーに事前に通知するものとします。

## 第13条（保証の否認及び免責） 

1. 当団体は、本サービスが登録ユーザーの特定の目的に適合すること、期待する機能・商品的価値・正確性・有用性を有すること、登録ユーザーによる本サービスの利用が登録ユーザーに適用のある法令または業界団体の内部規則等に適合すること、第三者の知的財産権、肖像権、プライバシーの権利、名誉、その他の権利または利益を侵害しないこと、継続的に利用できること、及び不具合が生じないことについて、明示または黙示を問わず何ら保証するものではありません。

2. 当団体は、当団体に故意または重過失がある場合を除き、本サービスに関して登録ユーザーが被った損害について、過去12ヶ月間に登録ユーザーが当団体に支払った対価の金額を超えて賠償する責任を負わないものとします。

3. 本サービスまたは当団体ウェブサイトに関連して登録ユーザーと他の登録ユーザーまたは第三者との間において生じた取引、連絡、紛争等については、登録ユーザーが自己の責任によって解決するものとします。

## 第14条（秘密保持）
登録ユーザーは、本サービスに関連して当団体が登録ユーザーに対して秘密に取扱うことを求めて開示した非公知の情報について、当団体の事前の書面による承諾がある場合を除き、秘密に取扱うものとします。

## 第15条（利用者情報の取扱い） 

1. 当団体による登録ユーザーの利用者情報の取扱いについては、別途当団体プライバシーポリシー（[https://cba-toolbox.github.io/CBAT/terms.html](https://cba-toolbox.github.io/CBAT/terms.html)）の定めによるものとし、登録ユーザーはこのプライバシーポリシーに従って当団体が登録ユーザーの利用者情報を取扱うことについて同意するものとします。

2. 当団体は、登録ユーザーが当団体に提供した情報、データ等を、個人を特定できない形での統計的な情報として、当団体の裁量で、利用及び公開することができるものとし、登録ユーザーはこれに異議を唱えないものとします。

## 第16条（本規約等の変更） 

1. 当団体は、当団体が必要と認めた場合に、本規約を変更できるものとします。

2. 本規約を変更する場合、変更後の本規約の施行時期及び内容を当団体ウェブサイト上での掲示その他の適切な方法により周知し、または登録ユーザーに通知します。

3. 法令上登録ユーザーの同意が必要となる本規約の変更を行う場合、当団体は、当団体所定の方法で登録ユーザーの同意を得るものとします。

4. 本規約の変更及びその通知（同条2項）後、登録ユーザーが本サービスにログインした場合には、前項の同意があったものとみなします。

## 第17条（連絡／通知） 

1. 本サービスに関する問い合わせその他登録ユーザーから当団体に対する連絡または通知、及び本規約の変更に関する通知その他当団体から登録ユーザーに対する連絡または通知は、当団体の定める方法で行うものとします。

2. 当団体が登録事項に含まれるメールアドレスその他の連絡先に連絡または通知を行った場合、登録ユーザーは当該連絡または通知を受領したものとみなします。

## 第18条（サービス利用契約上の地位の譲渡等） 

1. 登録ユーザーは、当団体の書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務につき、第三者に対し、譲渡、移転、担保設定、その他の処分をすることはできません。

2. 当団体は本サービスにかかる事業を他団体等に譲渡した場合には、当該事業譲渡に伴い利用契約上の地位、本規約に基づく権利及び義務並びに登録ユーザーの登録事項その他の顧客情報を当該事業譲渡の譲受人に譲渡することができるものとし、登録ユーザーは、かかる譲渡につき本項において予め同意したものとします。なお、本項に定める事業譲渡には、通常の事業譲渡のみならず、団体の分割その他事業が移転するあらゆる場合を含むものとします。

## 第19条（分離可能性）
本規約のいずれかの条項またはその一部が、法令等により無効または執行不能と判断された場合であっても、本規約の残りの規定及び一部が無効または執行不能と判断された規定の残りの部分は、継続して完全に効力を有するものとします。

## 第20条（準拠法及び裁判管轄） 

1. 本規約及びサービス利用契約の準拠法は日本法とします。 

2. 本規約またはサービス利用契約に起因し、または関連する一切の紛争については、東京地方裁判所を第一審の専属的合意管轄裁判所とします。

【2025年9月1日制定】

# プライバシーポリシー

計算論的精神医学コロキウム（以下「当団体」といいます。）は、当団体の提供するサービス（以下「本サービス」といいます。）における、ユーザーについての個人情報を含む利用者情報の取扱いについて、以下のとおりプライバシーポリシー（以下「本ポリシー」といいます。）を定めます。 

## 1.収集する利用者情報及び収集方法

本ポリシーにおいて、「利用者情報」とは、ユーザーの識別に係る情報、通信サービス上の行動履歴、その他ユーザーまたはユーザーの端末に関連して生成または蓄積された情報であって、本ポリシーに基づき当団体が収集するものを意味するものとします。本サービスにおいて当団体が収集する利用者情報は、その収集方法に応じて、以下のようなものとなります。

(1) ユーザーからご提供いただく情報

本サービスを利用するために、または本サービスの利用を通じてユーザーからご提供いただく情報は以下のとおりです。

- メールアドレス ・本サービスにおけるコンテンツのダウンロード回数
- 入力フォームその他当社が定める方法を通じてユーザーが入力または送信する情報

(2) ユーザーが本サービスの利用において、他のサービスと連携を許可することにより、当該他のサービスからご提供いただく情報

ユーザーが、本サービスを利用するにあたり、ソーシャルネットワーキングサービス等の他のサービスとの連携を許可した場合には、その許可の際にご同意いただいた内容に基づき、以下の情報を当該外部サービスから収集します。

- 当該外部サービスでユーザーが利用するID
- その他当該外部サービスのプライバシー設定によりユーザーが連携先に開示を認めた情報

(3) ユーザーが本サービスを利用するにあたって、当団体が収集する情報

当団体は、本サービスへのアクセス状況やそのご利用方法に関する情報を収集することがあります。これには以下の情報が含まれます。

- リファラ ・IPアドレス ・サーバーアクセスログに関する情報
- Cookie、ADID、IDFAその他の識別子（以下「Cookie等」といいます。）

## 2.  利用目的

本サービスのサービス提供にかかわる利用者情報の具体的な利用目的は以下のとおりです。

（1）本サービスに関する登録の受付、本人確認、ユーザー認証、ユーザー設定の記録、利用料金の決済計算等本サービスの提供、維持、保護及び改善のため

（2） ユーザーのトラフィック測定及び行動測定のため 

（3）本サービスに関するご案内、お問い合わせ等への対応のため 

（4）本サービスに関する当社の規約、ポリシー等（以下「規約等」といいます。）に違反する行為に対する対応のため

（5） 本サービスに関する規約等の変更などを通知するため

## 3.  第三者提供 

3-1 当団体は、利用者情報のうち、個人情報については、あらかじめユーザーの同意を得ないで、第三者に提供しません。但し、次に掲げる必要があり第三者に提供する場合はこの限りではありません。

（1）当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合

（2）合併その他の事由による事業の承継に伴って個人情報が提供される場合

（3）その他、個人情報の保護に関する法律（以下「個人情報保護法」といいます。）その他の法令で認められる場合

3-2 当団体は、個人情報を第三者に提供したときは、記録の作成及び保存を行います。

3-3 当団体は、第三者から個人情報の提供を受けるに際しては、必要な確認を行い、当該確認にかかる記録の作成及び保存を行うものとします。

3-4 以下の者は、同条で定める「第三者」に該当しません。

- 当団体の管理者
- 当団体の管理者が認める運営者
- 当団体が委任する弁護士

## 4.  安全管理措置

4-1　当団体は、利用者情報の漏えい、滅失または毀損の防止その他の利用者情報の安全管理のために、必要かつ適切な措置を講じています。

4-2　当団体は、利用者情報のうち個人情報の取扱いを第三者に委託する場合には、当団体が定める委託先選定基準を満たす事業者を選定し、委託契約を締結した上で定期的に報告を受ける等の方法により、委託先事業者による個人情報の取扱いについて把握しています。

4-3　当団体が講じる安全管理措置の具体的な内容については、本プライバシーポリシーに記載の当団体のお問合せ窓口にお問い合わせください。

## 5.  個人情報の開示等の請求 

5-1 当団体は、ユーザーから、個人情報保護法の定めに基づき保有個人データの利用目的の通知、保有個人データ又は第三者提供の記録の開示、保有個人データの内容の訂正・追加・削除、保有個人データの利用の停止・消去・第三者提供の停止のご請求（あわせて以下「個人情報の開示等の請求」といいます。）があった場合は、ユーザーご本人からのご請求であることを確認した上で、当団体所定の手続きに従い、遅滞なくこれらに対応いたします。 
    
5-2 利用目的の通知、保有個人データ又は第三者提供の記録の開示につきましては、手数料として【ご請求1件につき1,000円（消費税別）】をお支払いいただきます。

5-3 個人情報の開示等の請求の具体的な方法については、本プライバシーポリシーに記載の当団体のお問い合わせ窓口にお問い合わせください。

## 6.  お問い合わせ窓口

本サービスに対するご意見、ご質問、苦情のお申出その他利用者情報の取扱いに関するお問い合わせは、下記の窓口までお願いいたします。

計算論的精神医学コロキウム 

cba.toolbox   (at)   gmail.com 

## 7.  プライバシーポリシーの変更手続

当団体は、必要に応じて、本ポリシーを変更します。但し、法令上ユーザーの同意が必要となるような本ポリシーの変更を行う場合、変更後の本ポリシーは、当団体所定の方法で変更に同意したユーザーに対してのみ適用されるものとします。なお、当団体は、本ポリシーを変更する場合には、変更後の本ポリシーの施行時期及び内容を当団体のウェブサイト上での表示その他の適切な方法により周知し、またはユーザーに通知します。

【2025年9月1日制定】
